username = input("Имя пользователя ")
title = input("Заголовок заметки ")
content = input("Описание заметки ")
status = input("Статус заметки ")
created_date = input("Дата создания заметки: ")
issue_date = input("Дата истечения заметки: ")
print ('имя пользователя:', username)
print ("заголовок заметки:", title)
print ("описание заметки:", content)
print ("статус заметки:", status)
print ("Дата создания заметки: ", created_date[0:5])
print ("Дата истечения заметки:", issue_date[0:5])